Page({
  data:{profile:{},avatarSrc:'/assets/icons/default-collector-avatar.svg',name:'',account:'',password:'',confirmPassword:'',currentPassword:'',newPassword:'',error:''},
  onShow(){this.load()},input(e){this.setData({[e.currentTarget.dataset.field]:e.detail.value})},
  async load(){try{const profile=await getApp().globalData.session.refreshProfile();this.setData({profile,name:profile.name||'',account:profile.account||''});if(profile.hasCustomAvatar)this.setData({avatarSrc:await getApp().globalData.api.avatar()})}catch(e){this.setData({error:e.message})}},
  async save(){const name=this.data.name.trim();if(!name)return this.setData({error:'请填写姓名'});try{if(!this.data.profile.profileComplete){if(this.data.password!==this.data.confirmPassword)return this.setData({error:'两次输入的密码不一致'});await getApp().globalData.session.completeProfile({name,account:this.data.account,password:this.data.password});wx.showToast({title:'资料已完成'})}else{await getApp().globalData.session.setName(name);wx.showToast({title:'姓名已更新'})}await this.load()}catch(e){this.setData({error:e.message})}},
  async changePassword(){try{await getApp().globalData.api.changePassword({currentPassword:this.data.currentPassword,newPassword:this.data.newPassword});getApp().globalData.session.clear();wx.showModal({title:'密码已修改',content:'请使用新密码重新登录',showCancel:false,success:()=>wx.reLaunch({url:'/pages/login/index'})})}catch(e){this.setData({error:e.message})}},
  chooseAvatar(e){if(e.detail.avatarUrl)this.upload(e.detail.avatarUrl)},async upload(path){try{const profile=await getApp().globalData.api.uploadAvatar(path);this.setData({profile,avatarSrc:path});wx.showToast({title:'头像已更新'})}catch(e){this.setData({error:e.message||'头像上传失败'})}},
  async restoreAvatar(){try{const profile=await getApp().globalData.api.deleteAvatar();this.setData({profile,avatarSrc:'/assets/icons/default-collector-avatar.svg'});wx.showToast({title:'已恢复默认头像'})}catch(e){this.setData({error:e.message})}}
})
