<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRoute,useRouter } from 'vue-router'
import PageActions from '../../../components/admin/PageActions.vue'; import { platformApi } from '../../../lib/platformApi.js'; import { taskApi } from '../../../lib/taskApi.js'; import { operationId } from '../../../lib/apiUtils.js'
const route=useRoute(),router=useRouter(),platforms=ref([]),error=ref(''),saving=ref(false)
const form=reactive({taskCode:'',platformId:'',name:'',description:'',referenceTypes:['TEXT'],textInputEnabled:false,humanReviewEnabled:true,recordingFormat:'WAV',sampleRate:16000,minDurationMillis:1000,maxDurationMillis:600000,rejectionReasons:'空音频,内容不符'})
async function init(){try{platforms.value=(await platformApi.list(0,100)).items||[];if(route.params.id){const [t,versions]=await Promise.all([taskApi.get(route.params.id),taskApi.versions(route.params.id)]);const v=versions.find(row=>row.id===t.currentVersionId)||versions.at(-1);Object.assign(form,{taskCode:t.taskCode,platformId:t.platformId,name:t.name,description:t.description||'',referenceTypes:[...(v?.referenceTypes||['TEXT'])],textInputEnabled:!!v?.textInputEnabled,humanReviewEnabled:v?.humanReviewEnabled!==false,recordingFormat:v?.recordingFormat||'WAV',sampleRate:[...(v?.sampleRates||[16000])][0],minDurationMillis:v?.minDurationMillis||1000,maxDurationMillis:v?.maxDurationMillis||600000,rejectionReasons:(v?.rejectionReasons||[]).join(',')})}}catch(e){error.value=e.message}}
function payload(){return{name:form.name,description:form.description,version:{referenceTypes:form.referenceTypes,fixedRecording:true,textInputEnabled:form.textInputEnabled,humanReviewEnabled:form.humanReviewEnabled,recordingFormat:form.recordingFormat,sampleRates:[Number(form.sampleRate)],channels:1,minDurationMillis:Number(form.minDurationMillis),maxDurationMillis:Number(form.maxDurationMillis),rejectionReasons:form.rejectionReasons.split(',').map(v=>v.trim()).filter(Boolean),aiEnabled:false}}}
async function save(){if(!form.referenceTypes.length){error.value='至少选择一种参考源';return}saving.value=true;error.value='';try{if(route.params.id)await taskApi.update(route.params.id,payload(),operationId('task-update'));else await taskApi.create({taskCode:form.taskCode,platformId:form.platformId,...payload()},operationId('task-create'));router.push('/admin/tasks')}catch(e){error.value=e.message}finally{saving.value=false}}
onMounted(init)
</script>
<template><section class="admin-page"><PageActions :title="route.params.id?'编辑任务版本':'创建任务'" description="录音为固定能力；文字输入和人工审核按任务配置。" /><form class="business-card business-form business-form-wide" @submit.prevent="save"><div class="business-form-grid"><label>任务编号<input v-model.trim="form.taskCode" :disabled="!!route.params.id" required /></label><label>来源平台<select v-model="form.platformId" required><option value="">请选择</option><option v-for="p in platforms" :key="p.id" :value="p.id">{{ p.name }}</option></select></label><label>任务名称<input v-model.trim="form.name" required /></label><label>录音格式<select v-model="form.recordingFormat"><option>WAV</option><option>MP3</option></select></label><label>采样率<select v-model.number="form.sampleRate"><option :value="8000">8000Hz</option><option :value="16000">16000Hz</option><option :value="44100">44100Hz</option><option :value="48000">48000Hz</option></select></label><label>最短时长(ms)<input v-model.number="form.minDurationMillis" type="number" min="1" /></label><label>最长时长(ms)<input v-model.number="form.maxDurationMillis" type="number" min="1" /></label><label class="business-span">说明<textarea v-model="form.description" rows="3" /></label></div><fieldset><legend>参考源（至少一项）</legend><label v-for="type in ['TEXT','AUDIO','VIDEO']" :key="type" class="business-check"><input v-model="form.referenceTypes" type="checkbox" :value="type" />{{ type }}</label></fieldset><fieldset><legend>采集与审核</legend><label class="business-check"><input checked disabled type="checkbox" />录音（固定）</label><label class="business-check"><input v-model="form.textInputEnabled" type="checkbox" />允许文字输入</label><label class="business-check"><input v-model="form.humanReviewEnabled" type="checkbox" />人工审核</label></fieldset><label>驳回预设原因（逗号分隔）<input v-model="form.rejectionReasons" /></label><p class="business-note">首期 AI 功能不展示且固定关闭。</p><p v-if="error" class="business-error">{{ error }}</p><div class="business-actions"><router-link class="button-secondary" to="/admin/tasks">取消</router-link><button class="button-primary" :disabled="saving">{{ saving?'保存中…':'保存' }}</button></div></form></section></template>
