<script setup>
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import PageActions from '../../../components/admin/PageActions.vue'; import AsyncState from '../../../components/admin/AsyncState.vue'; import { taskApi } from '../../../lib/taskApi.js'; import { userApi } from '../../../lib/userApi.js'; import { operationId } from '../../../lib/apiUtils.js'
const route=useRoute(),query=ref(''),users=ref([]),grants=ref([]),requests=ref([]),error=ref(''),loading=ref(false)
async function load(){loading.value=true;try{grants.value=(await taskApi.grants(route.params.id,0,100)).items||[];requests.value=(await taskApi.accessRequests(route.params.id,0,100)).items||[]}catch(e){error.value=e.message}finally{loading.value=false}}
async function search(){try{users.value=(await userApi.search({query:query.value,role:'COLLECTOR',page:0,size:50})).content||[]}catch(e){error.value=e.message}}
async function grant(user){try{await taskApi.grant(route.params.id,user.id,operationId('grant'));await load()}catch(e){error.value=e.message}}
async function revoke(row){if(!confirm('确认撤销该用户的新领取权限？已领取数据仍可完成。'))return;try{await taskApi.revokeGrant(route.params.id,row.userId,operationId('grant-revoke'));await load()}catch(e){error.value=e.message}}
async function decide(row,action){try{await taskApi.decideAccess(route.params.id,row.id,action,action==='reject'?'管理员驳回':'',operationId(`access-${action}`));await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="admin-page"><PageActions title="采集权限" description="按用户姓名或系统用户 ID 搜索，也可处理小程序端申请。"><router-link class="button-secondary" :to="`/admin/tasks/${route.params.id}`">返回任务</router-link></PageActions><p v-if="error" class="business-error">{{ error }}</p><div class="business-grid"><div class="business-card"><h3>直接授权</h3><form class="business-inline" @submit.prevent="search"><input v-model.trim="query" placeholder="姓名或用户 ID"/><button class="button-primary">搜索</button></form><div v-if="users.length" class="business-list"><div v-for="u in users" :key="u.id"><span><strong>{{ u.name }}</strong><small>{{ u.internalUserNo }}</small></span><button class="button-link" @click="grant(u)">授权</button></div></div><p v-else class="business-note">输入条件搜索采集员。</p></div><div class="business-card"><h3>待审批申请</h3><AsyncState :loading="loading" :error="''" :empty="!requests.length"><div class="business-list"><div v-for="r in requests" :key="r.id"><span><strong>{{ r.userId }}</strong><small>{{ r.status }}</small></span><span><button class="button-link" @click="decide(r,'approve')">通过</button><button class="button-link is-danger" @click="decide(r,'reject')">驳回</button></span></div></div></AsyncState></div></div><div class="business-card"><h3>已授权用户</h3><AsyncState :loading="loading" :error="''" :empty="!grants.length"><div class="business-table-wrap"><table class="business-table"><thead><tr><th>用户 ID</th><th>状态</th><th>授权时间</th><th>操作</th></tr></thead><tbody><tr v-for="g in grants" :key="g.id"><td>{{ g.userId }}</td><td>{{ g.status }}</td><td>{{ g.createdAt }}</td><td><button v-if="g.status==='ACTIVE'" class="button-link is-danger" @click="revoke(g)">撤销</button></td></tr></tbody></table></div></AsyncState></div></section></template>
