const { validateSubmission } = require('../../services/recorder.js')
const { createRecordingSession } = require('../../services/recordingSession.js')
const feedback = require('../../services/feedback.js')
function durationText(ms){const seconds=Math.round((ms||0)/1000);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
Page({
  data:{item:{},version:{},loading:true,error:'',referenceAudioPath:'',referenceVideoPath:'',audioPath:'',audioDuration:0,audioDurationText:'00:00',text:'',recordState:'idle',levelBars:[0,0,0,0,0,0,0],submitting:false,releasing:false,statusText:'待录制'},
  onLoad(options){this.itemId=options.itemId;this.load()},
  async onUnload(){await this.session?.dispose()},
  setupRecorder(){this.session=createRecordingSession({recorder:wx.getRecorderManager(),fs:wx.getFileSystemManager(),userDataPath:wx.env.USER_DATA_PATH,version:this.data.version,onLevel:level=>{const active=Math.ceil(level*7);this.setData({levelBars:this.data.levelBars.map((_,i)=>i<active?Math.max(18,Math.round(level*100)):8)})},onState:recordState=>this.setData({recordState}),onComplete:result=>this.setData({audioPath:result.filePath,audioDuration:result.durationMillis,audioDurationText:durationText(result.durationMillis)}),onError:error=>{const message=error.message||'录音保存失败';this.setData({error:message,audioPath:'',audioDuration:0,audioDurationText:'00:00'});feedback.error(message)}})},
  async load(){if(!this.itemId){this.setData({loading:false,error:'缺少作业编号'});return}try{const api=getApp().globalData.api,item=await api.item(this.itemId),versions=await api.versions(item.taskId),version=versions.find(x=>x.id===item.taskVersionId)||{};this.setData({item,version,text:item.currentResult?.text||'',statusText:item.status==='REWORK_PENDING'?'待返修':'待录制'});this.setupRecorder();const[audio,video]=await Promise.all([api.media(item.referenceAudioMediaId),api.media(item.referenceVideoMediaId)]);this.setData({referenceAudioPath:audio,referenceVideoPath:video})}catch(e){this.setData({error:e.message||'加载作业失败'})}finally{this.setData({loading:false})}},
  startRecord(){this.setData({error:'',audioPath:'',audioDuration:0,audioDurationText:'00:00'});this.session.start()},pauseRecord(){this.session.pause()},resumeRecord(){this.session.resume()},async stopRecord(){try{const result=await this.session.stop();this.setData({audioPath:result.filePath,audioDuration:result.durationMillis,audioDurationText:durationText(result.durationMillis)})}catch(e){this.setData({error:e.message||'录音保存失败'})}},
  textInput(e){this.setData({text:e.detail.value})},
  async submit(){const validation=validateSubmission(this.data.version,{audio:this.data.audioPath,text:this.data.text});if(validation){this.setData({error:validation.message});return}this.setData({submitting:true,error:''});const api=getApp().globalData.api;try{await api.submit(this.itemId,{operationId:api.operationId('submit'),assignmentId:this.data.item.assignmentId,expectedRevision:this.data.item.revision,text:this.data.text.trim(),audioPath:this.data.audioPath});wx.removeStorageSync('currentTaskItemId');feedback.success('提交成功');setTimeout(()=>wx.navigateBack({delta:1}),450)}catch(e){this.setData({error:e.message||'提交失败'});feedback.error(e.message||'提交失败')}finally{this.setData({submitting:false})}},
  release(){wx.showModal({title:'释放到数据池',content:'是否释放回数据池？当前未提交结果将被清除，操作历史仍保留。',confirmColor:'#c2413b',success:async result=>{if(!result.confirm)return;this.setData({releasing:true,error:''});try{const api=getApp().globalData.api;await api.release(this.itemId,this.data.item.revision,api.operationId('release'));wx.removeStorageSync('currentTaskItemId');feedback.success('已释放到数据池');setTimeout(()=>wx.navigateBack({delta:1}),400)}catch(e){this.setData({error:e.message||'释放失败'});feedback.error(e.message)}finally{this.setData({releasing:false})}}})},
  durationText
})
