const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const read = file => fs.readFileSync(file, 'utf8')

test('任务大厅与任务数据页使用三段流程', () => {
	const hall = read('pages/tasks/index.wxml')
	const hallScript = read('pages/tasks/index.js')
	const listScript = read('pages/work-list/index.js')
	const listPage = read('pages/work-list/index.wxml')
	assert.match(hall, /查看任务/)
	assert.doesNotMatch(hall, /查看待办/)
	assert.doesNotMatch(hall, /当前有未完成作业|每位采集员同时只能占用一条|continueWork/)
	assert.doesNotMatch(hallScript, /currentItemId|currentTaskItemId|continueWork/)
	for (const script of ['pages/tasks/index.js', 'pages/work/index.js', 'pages/profile/index.js']) {
		assert.doesNotMatch(read(script), /currentTaskItemId/)
	}
	assert.match(listScript, /PENDING.*待处理.*SUBMITTED.*已提交.*FINISHED.*已完成/s)
	assert.match(listPage, /任务数据/)
	assert.match(listPage, /待审核/)
	assert.match(listPage, /已完成/)
})

test('作业页区分可编辑和只读状态并使用本地 SVG 图标', () => {
	const script = read('pages/work/index.js')
	const page = read('pages/work/index.wxml')
	const config = JSON.parse(read('pages/work/index.json'))
	const style = read('pages/work/index.wxss')
	assert.match(script, /editable/)
	assert.match(script, /readOnly/)
	assert.match(script, /SUBMITTED/)
	assert.match(script, /STALE_STATE/)
	assert.equal(config.usingComponents['audio-player'], '../../components/audio-player/index')
	assert.equal((page.match(/<audio-player/g) || []).length, 3)
	assert.doesNotMatch(page, /<audio(?:\s|>)/)
	assert.match(script, /require\('\.\.\/\.\.\/services\/pcm\.js'\)/)
	assert.doesNotMatch(script, /services\/waveform\.js/)
	assert.equal(fs.existsSync('services/waveform.js'), false)
	assert.match(script, /levelBars:\s*waveformBars\(0\)/)
	assert.match(script, /onLevel:\s*level\s*=>\s*this\.setData\(\{\s*levelBars:\s*waveformBars\(level\)\s*\}\)/)
	assert.doesNotMatch(script, /i\s*<\s*active/)
	assert.match(page, /assets\/icons\/iconfont\/microphone\.svg/)
	assert.match(page, /assets\/icons\/iconfont\/trash\.svg/)
	assert.match(page, /assets\/icons\/iconfont\/pause\.svg/)
	assert.match(page, /assets\/icons\/iconfont\/resume\.svg/)
	assert.match(page, /assets\/icons\/iconfont\/stop\.svg/)
	assert.doesNotMatch(page, /🎙|🗑|Ⅱ|■/)
	assert.match(page, /点击开始录音/)
	assert.match(page, /录音中/)
	assert.match(page, /已暂停/)
	assert.match(style, /\.recorder-stage\{[^}]*min-height:/)
	assert.match(style, /\.record-control\{[^}]*width:[^;}]+;[^}]*height:/)
	assert.match(page, /wx:if="{{editable}}"/)
	assert.match(page, /wx:if="{{readOnly}}"/)
})

test('Iconfont 本地资源记录来源与许可', () => {
	const notice = read('assets/icons/iconfont/README.md')
	assert.match(notice, /iconfont\.cn/)
	assert.match(notice, /许可|授权/)
	assert.ok(fs.existsSync('assets/icons/iconfont/microphone.svg'))
	assert.ok(fs.existsSync('assets/icons/iconfont/trash.svg'))
	assert.ok(fs.existsSync('assets/icons/iconfont/play.svg'))
	assert.ok(fs.existsSync('assets/icons/iconfont/pause.svg'))
	assert.ok(fs.existsSync('assets/icons/iconfont/stop.svg'))
})

test('自定义播放器使用单一时间、可拖动进度和本地图标', () => {
	assert.ok(fs.existsSync('components/audio-player/index.js'))
	assert.ok(fs.existsSync('components/audio-player/index.wxml'))
	assert.ok(fs.existsSync('components/audio-player/index.wxss'))
	const config = JSON.parse(read('components/audio-player/index.json'))
	const component = read('components/audio-player/index.wxml')
	const script = read('components/audio-player/index.js')
	assert.equal(config.component, true)
	assert.match(component, /assets\/icons\/iconfont\/play\.svg/)
	assert.match(component, /assets\/icons\/iconfont\/pause\.svg/)
	assert.match(component, /<slider[^>]*bindchange="seek"/)
	assert.equal((component.match(/{{timeText}}/g) || []).length, 1)
	assert.match(script, /createAudioPlayback/)
	assert.match(script, /createInnerAudioContext/)
	assert.match(script, /triggerEvent\('error'/)
	assert.match(script, /onState:\s*\(\{\s*playing,\s*progress,\s*timeText\s*\}\)\s*=>\s*this\.setData\(\{\s*playing,\s*progress,\s*timeText\s*\}\)/)
	assert.doesNotMatch(script, /this\.setData\(state\)/)
})
