const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const read = file => fs.readFileSync(path.resolve(file), 'utf8')

test('任务数据固定每页十条并由页面计算分页边界', () => {
  const script = read('pages/work-list/index.js')
  assert.match(script, /const PAGE_SIZE=10/)
  assert.match(script, /const pageCount=total=>Math\.max\(1,Math\.ceil/)
  assert.doesNotMatch(script, /require\('\.\/pagination\.js'\)/)
  assert.equal(fs.existsSync(path.resolve('pages/work-list/pagination.js')), false)
})

test('任务数据页提供原生页码选择器并在切换页签时回到第一页', () => {
  const script = read('pages/work-list/index.js')
  const page = read('pages/work-list/index.wxml')
  const style = read('pages/work-list/index.wxss')

  assert.match(script, /size:PAGE_SIZE/)
  assert.match(script, /previousPage\(\)/)
  assert.match(script, /nextPage\(\)/)
  assert.match(script, /pageOptions:\['第 1 页'\]/)
  assert.match(script, /selectPage\(e\)/)
  assert.match(script, /Number\.isInteger\(target\)/)
  assert.match(script, /kind,page:0/)
  assert.match(script, /onPullDownRefresh\(\)\{this\.load\(this\.data\.page\)/)
  assert.match(page, /bindtap="previousPage"/)
  assert.match(page, /按最新修改时间倒序排列/)
  assert.match(page, /<picker[^>]*mode="selector"[^>]*range="\{\{pageOptions\}\}"[^>]*value="\{\{page\}\}"/)
  assert.match(page, /bindchange="selectPage"/)
  assert.match(page, /第 \{\{page\+1\}\} 页 \/ 共 \{\{totalPages\}\} 页/)
  assert.match(page, /bindtap="nextPage"/)
  assert.match(page, /disabled="\{\{loading\|\|page===0\}\}"/)
  assert.match(page, /disabled="\{\{loading\|\|page\+1>=totalPages\}\}"/)
  assert.match(style, /\.pagination\{[^}]*flex-wrap:wrap/)
  assert.match(style, /\.page-picker\{[^}]*flex:/)
})
