<script setup>
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import AsyncState from '../../../components/admin/AsyncState.vue'; import PageActions from '../../../components/admin/PageActions.vue'; import { reviewApi } from '../../../lib/reviewApi.js'; import { operationId } from '../../../lib/apiUtils.js'
import { useAdminSession } from '../../../composables/useAdminSession.js'
import PaginationControls from '../../../components/admin/PaginationControls.vue'
const router=useRouter(),session=useAdminSession(),rows=ref([]),loading=ref(false),error=ref(''),count=ref(5),selected=ref(new Set()),notice=ref(''),page=ref(0),total=ref(0)
async function load(){loading.value=true;error.value='';try{const result=await reviewApi.pool(page.value,20);rows.value=result.items||[];total.value=result.total||0}catch(e){error.value=e.message}finally{loading.value=false}}
function changePage(value){page.value=value;selected.value=new Set();load()}
async function claim(){try{const item=await reviewApi.claim(operationId('review-claim'));router.push(`/admin/review/${item.id}`)}catch(e){error.value=e.message}}
async function claimBatch(){try{const items=await reviewApi.claimBatch(Number(count.value),operationId('review-claim-batch'));if(items[0])router.push(`/admin/review/${items[0].id}`);else await load()}catch(e){error.value=e.message}}
function toggle(row){const next=new Set(selected.value);next.has(row.id)?next.delete(row.id):next.add(row.id);selected.value=next}
async function batchApprove(){if(!selected.value.size||!confirm(`确认批量通过 ${selected.value.size} 条审核数据？`))return;try{const commands=rows.value.filter(r=>selected.value.has(r.id)).map(r=>({itemId:r.id,expectedRevision:r.revision,text:r.currentResult?.text||null}));const result=await reviewApi.batchApprove(commands,operationId('review-batch-approve'));notice.value=`批量通过完成：成功 ${result.filter(r=>r.success).length}，冲突 ${result.filter(r=>!r.success).length}`;selected.value=new Set();await load()}catch(e){error.value=e.message}}
async function assign(row){const reviewerId=prompt('请输入审核员用户 ID');if(!reviewerId)return;try{await reviewApi.assign(row.id,reviewerId,row.revision,operationId('review-assign'));await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="admin-page"><PageActions title="审核池" description="审核员可随机领取，管理员可进行批量处理。"><button class="button-secondary" @click="load">刷新</button><button class="button-primary" @click="claim">领取一条</button></PageActions><div class="business-card"><div class="business-inline"><label>批量领取数量 <input v-model.number="count" type="number" min="1" max="100" /></label><button class="button-secondary" @click="claimBatch">批量领取</button><button v-if="session.user.value?.role==='ADMIN'" class="button-secondary" :disabled="!selected.size" @click="batchApprove">批量通过</button></div><p v-if="notice" class="business-success">{{notice}}</p><AsyncState :loading="loading" :error="error" :empty="!rows.length" empty-text="当前没有待审核数据" @retry="load"><div class="business-table-wrap"><table class="business-table"><thead><tr><th v-if="session.user.value?.role==='ADMIN'">选择</th><th>条目</th><th>任务</th><th>采集员</th><th>文字</th><th>时长</th><th></th></tr></thead><tbody><tr v-for="r in rows" :key="r.id"><td v-if="session.user.value?.role==='ADMIN'"><input type="checkbox" :checked="selected.has(r.id)" @change="toggle(r)"/></td><td>{{ r.itemCode }}</td><td>{{ r.taskId }}</td><td>{{ r.collectorId }}</td><td>{{ r.currentResult?.text?'有':'无' }}</td><td>{{ r.currentResult?.audio?.durationMillis||0 }}ms</td><td><button v-if="session.user.value?.role==='ADMIN'" class="button-link" @click="assign(r)">分配</button><router-link class="button-link" :to="`/admin/review/${r.id}`">审核</router-link></td></tr></tbody></table></div><PaginationControls :page="page" :total="total" :size="20" @change="changePage"/></AsyncState></div></section></template>
