<script setup>
import { computed, onMounted, ref } from 'vue'; import { useRoute,useRouter } from 'vue-router'; import AsyncState from '../../../components/admin/AsyncState.vue'; import PageActions from '../../../components/admin/PageActions.vue'; import { taskApi } from '../../../lib/taskApi.js'; import { reviewApi } from '../../../lib/reviewApi.js'; import { operationId } from '../../../lib/apiUtils.js'
const route=useRoute(),router=useRouter(),item=ref(null),version=ref(null),loading=ref(false),error=ref(''),text=ref(''),reasons=ref([]),note=ref('')
const audioUrl=computed(()=>item.value?.currentResult?.audio?.mediaId?`/api/media/${encodeURIComponent(item.value.currentResult.audio.mediaId)}`:'')
async function load(){loading.value=true;try{item.value=await taskApi.item(route.params.itemId);const versions=await taskApi.versions(item.value.taskId);version.value=versions.find(v=>v.id===item.value.taskVersionId);text.value=item.value.currentResult?.text||''}catch(e){error.value=e.message}finally{loading.value=false}}
async function approve(){try{await reviewApi.approve(item.value.id,item.value.revision,text.value,operationId('review-approve'));router.push('/admin/review/queue')}catch(e){error.value=e.message}}
async function reject(){if(!reasons.value.length&&!note.value.trim()){error.value='至少选择一个驳回原因或填写补充说明';return}try{await reviewApi.reject(item.value.id,item.value.revision,reasons.value,note.value,operationId('review-reject'));router.push('/admin/review/queue')}catch(e){error.value=e.message}}
async function release(){if(!confirm('确认释放审核领取？采集结果不会删除。'))return;try{await reviewApi.release(item.value.id,item.value.revision,operationId('review-release'));router.push('/admin/review/queue')}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="admin-page"><PageActions title="审核工作台" description="对照参考源检查采集结果，可补改文字后通过。"><button class="button-secondary" @click="release">释放审核</button></PageActions><AsyncState :loading="loading" :error="error" :empty="!item" @retry="load"><div class="review-layout"><div class="business-card"><h3>参考源</h3><div v-if="item.referenceText" class="reference-text">{{ item.referenceText }}</div><audio v-if="item.referenceAudioMediaId" controls :src="`/api/media/${item.referenceAudioMediaId}`"/><video v-if="item.referenceVideoMediaId" controls :src="`/api/media/${item.referenceVideoMediaId}`"/><p v-if="!item.referenceText&&!item.referenceAudioMediaId&&!item.referenceVideoMediaId" class="business-note">无参考源</p></div><div class="business-card"><h3>采集结果</h3><audio v-if="audioUrl" controls :src="audioUrl"/><p v-else class="business-note">本条未提交音频</p><label>普通话文本<textarea v-model="text" rows="8" placeholder="可由审核员补充或修正"/></label></div><div class="business-card"><h3>审核结论</h3><div class="business-check-list"><label v-for="reason in version?.rejectionReasons||[]" :key="reason"><input v-model="reasons" type="checkbox" :value="reason"/>{{ reason }}</label></div><label>补充说明<textarea v-model="note" rows="4" /></label><p v-if="error" class="business-error">{{ error }}</p><div class="business-actions"><button class="button-secondary is-danger" @click="reject">驳回到采集环节</button><button class="button-primary" @click="approve">审核通过</button></div></div></div></AsyncState></section></template>
